name: Warps
version: 1.0.0
author: TurboBass
description: Everything Warps! 
main: io.GitHub.RamiHalabi.Warps.Main
commands:

  warp:
    description: Teleport to a warp location.
    usage: "Usage:  /warp <WarpName>"
    
  setWarp:
    description: Creates a warp location.
    usage: "Usage:  /setWarp <newLocation>"

  delWarp:
    description: Deletes a warp location.
    usage: "Usage:  /delwarp <WarpName>"
    
  back:
    description: Teleports you to where you last died/teleported!.
    usage: "Usage:  /back"

    
 